version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "alchemydc"
      - "arya2"
      - "gustavovalverde"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      zebra:
        patterns:
          - "zebra-*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      hickory:
        patterns:
          - "hickory-*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "alchemydc"
      - "arya2"
      - "gustavovalverde"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "alchemydc"
      - "arya2"
      - "gustavovalverde"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      docker:
        patterns:
          - "*"
